### ISSUE TITLE
Get rid of public/private key and replace with script

### ISSUE THREAD

**Issue by elear** [iot-onboarding/tiedie#1]
There is a private key in gateway/ca_certs/ca.key.  This is fine for testing but needs to be replaced by a script to generate the key pair.

**Comment by elear** [comment]
Don't close issue until all keys are gone.  There are still some lingering.

**Comment by rohitmohan96** [comment]
Pending: ca.pem and *.p12 files in the python sample app.

**Comment by rohitmohan96** [comment]
Closing since they have all been removed.
