### ISSUE TITLE
Compliance with draft-brinckman-nipc-00

### ISSUE THREAD

**Issue by rohitmohan96** [iot-onboarding/tiedie#7]
https://www.ietf.org/archive/id/draft-brinckman-nipc-00.html

**Comment by rohitmohan96** [comment]
#32 has the new versions for the existing features. 
Some of the few things that are left out are: 
1. Support for the new APIs: some GET APIs, register file, write with/without response, gatt caching, etc. 
2. Device grouping.

**Comment by elear** [comment]
Should this one be closed at this point?

**Comment by rohitmohan96** [comment]
Yes, we can close it.
